name: geojson_vi
description: GeoJSON package for Dart and Flutter developers to create, read, search, update and delete the geospatial data interchange format (GIS data).

version: 2.0.2
homepage: https://github.com/chuyentt/geojson_vi

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic:
  test:
